### ISSUE TITLE
Permission management on Postgres

### ISSUE THREAD

**Issue by frgfm** [dataforgoodfr/batch4_diafoirus_mimic#1]
Before running the SQL queries, we have to grant all privileges to user.
Otherwise, we run into the following error:
`ERROR:  permission denied for relation admissions`

Still trying to find the solution as 
`GRANT ALL PRIVILEGES ON TABLE admissions TO user;`
didn't work out

**Comment by edthrn** [comment]
@frgfm This is unexpected, as @florentpietot included the command for granting access to the appropriate `mimic` user in the `setup.sh`.

I would say that you probably tried to log in and execute queries *before* the build was totally done. Is it possible?

Note that you wouldn't necessarily have noticed, as Docker allows you to execute commands in the container's shell even if it hasn't completed the build yet...

**Comment by flrntpt** [comment]
@frgfm I'd suggest running `docker logs mimic` and see the results of this (see attached picture).

![screen shot 2018-04-02 at 22 40 11](https://user-images.githubusercontent.com/1823257/38215095-ee61961e-36c6-11e8-86b6-2c0172a9ce53.png)

If everything went well, you should have `PASSED` everywhere

**Comment by frgfm** [comment]
@edouardtheron I'll close the issue, the script was only slow but I thought it had crashed. Now it's working !
